# Generated by Django 5.1.11 on 2025-08-27 20:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gak_number', models.CharField(max_length=20)),
                ('gak_year', models.PositiveIntegerField()),
                ('procedure', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('pleading_type', models.CharField(blank=True, max_length=255)),
                ('eak_number', models.CharField(blank=True, max_length=20)),
                ('eak_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('solon_code', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.JSONField()),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scraper_version', models.CharField(default='v1', max_length=32)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='civil_app.case')),
            ],
        ),
        migrations.CreateModel(
            name='CivilSearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('gak_number', models.CharField(max_length=20)),
                ('gak_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('error_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='civil_app.case')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='civil_app.casesnapshot')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='civil_app.court')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='civil_app.court'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('court', 'gak_number', 'gak_year'), name='uniq_case_by_court_gak_year'),
        ),
    ]
