# Generated by Django 5.1.11 on 2025-08-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0002_civilsearchjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilsearchjob',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
